spring:
  datasource:
    url: jdbc:mysql://mysql-service:3306/micro_db?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
    username: testuser
    password: testpass
logging:
  level.org.springframework=INFO