spring:
  datasource:
    url: jdbc:mysql://mysql:3306/micro_db?createDatabaseIfNotExist=true
    username: root
    password: root
  application:
        name: server-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate-dialect: org.hibernate.dialect.MySQLDialect
      hibernate.format_sql: true
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411/
    collector:
      host: zipkin

  sleuth:
    sampler:
      probability: 1.0


token:
  jwt:
    secretKey: 413F4428472783999G9329HND9032MPENKSE9UND0303900291NNE0DNQ9WQWN0239NDE94B6250655368566D5970337336763979244226452948404D6351
springdoc:
  api-docs:
    enabled: true
    common:
      version: 1.0.0
      title: Sample Microservices API TEST
      description: Description of the API...
      termsOfService: MY TERMS OF SERVICE
      license: MY LICENSE
      licenseUrl: MY LICENSE URL
      externalDocDesc: MY WIKI PAGE
      externalDocUrl: MY WIKI URL
      contact:
        name: NAME OF CONTACT
        url: URL TO CONTACT
        email: contact@mail.com
    query-serv:
      description: "get list of all products from External DB"
      notes: |
        # Notes

        The service fetch list of MapStocOpt from external DB in purpose of updating owned DB

        The fetch will return :

        **1.** List of MapStocOpt object

        **2.** Will insert an entry in log.info with message :"Am reusit fetch din bd mapstoc" and the list.size

        # Test Title
          ljlljl
param:
  command-service: command-service
  query-service: query-service

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka
    fetch-registry: true
    register-with-eureka: true

metrics:
  distribution:
    percentiles-histogram:
      http:
        server:
          requests: true